# Generated by Django 5.1.4 on 2024-12-22 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=200)),
                ('welcome_message_ru', models.TextField(default='Здравствуйте! Добро пожаловать в M-CHAT-R бот.')),
                ('welcome_message_uz', models.TextField(default='Salom! M-CHAT-R botiga xush kelibsiz.')),
                ('welcome_message_en', models.TextField(default='Hello! Welcome to the M-CHAT-R bot.')),
                ('welcome_message_kk', models.TextField(default='Сәлем! M-CHAT-R ботына қош келдіңіз.')),
            ],
        ),
        migrations.CreateModel(
            name='MChatQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('question_text_ru', models.TextField()),
                ('question_text_uz', models.TextField()),
                ('question_text_en', models.TextField()),
                ('question_text_kk', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('language', models.CharField(default='ru', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_score', models.PositiveIntegerField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Низкий риск'), ('MEDIUM', 'Средний риск'), ('HIGH', 'Высокий риск')], max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.telegramuser')),
            ],
        ),
    ]
